DefaultContentLanguage = "en"
Paginate = "10"
SectionPagesMenu = "main"
baseURL = "/"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
theme = "gohugo-theme-ananke"
themesDir = "../.."
title = "Medical Articles"
[params]
background_color_class = "bg-black"
description = "The last theme you'll ever need. Maybe."
facebook = ""
favicon = ""
featured_image = "/uploads/cover.jpg"
github = ""
gitlab = ""
instagram = ""
linkedin = ""
mastodon = ""
recent_posts_number = "8"
rss = ""
site_logo = ""
slack = ""
stackoverflow = ""
twitter = ""
youtube = ""
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5
